aspnet-mvc-ads/Controllers/AdvertController.cs
using App.Data.Entity;
using App.Service.Abstract;
using App.Service.Concrete;
using aspnet_mvc_ads.Models;
using aspnet_mvc_ads.Utils;
using Microsoft.AspNetCore.Mvc;
using Microsoft.CodeAnalysis;


namespace aspnet_mvc_ads.Controllers
{
	public class AdvertController : Controller
	{
		public readonly ICategoryAdvertService _categoryAdvertService;
		public readonly IService<Category> _CategoryService;
		public readonly IAdvertService _advertService;
		public readonly IService<User> _UserService;
		public readonly IAdvertListingService _AdvertListingService;
        private readonly IService<AdvertComment> _serviceComment;
        private readonly IService<Advert> _serviceAdvert;


        public AdvertController(ICategoryAdvertService categoryAdvertService, IService<Category> categoryService, IAdvertService advertService, IService<User> userService, IAdvertListingService advertListingService, IService<AdvertComment> serviceComment, IService<Advert> serviceAdvert)
        {
            _categoryAdvertService = categoryAdvertService;
            _CategoryService = categoryService;
            _advertService = advertService;
            _UserService = userService;
            _AdvertListingService = advertListingService;
            _serviceComment = serviceComment;
            _serviceAdvert = serviceAdvert;
        }

        public async Task<IActionResult> Search(int CategoryId, string query = "")
		{
			var model = await _categoryAdvertService.GetAllAdvertsByCategory(CategoryId, query);

			ViewData["AllCategories"] = _CategoryService.GetAll();

			return View(model);

		}


		public IActionResult AddListing()
		{
			ViewData["Categories"] = _CategoryService.GetAll();
            ViewData["userName"] = Request.Cookies["userName"];
            ViewData["userPhone"] = Request.Cookies["userPhone"];
            ViewData["userEmail"] = Request.Cookies["userEmail"];
            ViewData["userAdress"] = Request.Cookies["userAdress"];
            return View();
		}


		[HttpPost]
        public async Task<IActionResult> AddListing(int categoryId, AddListingViewModel addListingView, List<IFormFile>? Images)
        {
            ViewData["Categories"] = _CategoryService.GetAll();
            ViewData["userName"] = Request.Cookies["userName"];
            ViewData["userPhone"] = Request.Cookies["userPhone"];
            ViewData["userEmail"] = Request.Cookies["userEmail"];
            ViewData["userAdress"] = Request.Cookies["userAdress"];


            var user = _UserService.Get(a => a.Email == Request.Cookies["userEmail"]);
            var category = _CategoryService.GetAll(c => c.Id == categoryId);

            List<AdvertImage> advertImages = new List<AdvertImage>();

            foreach (IFormFile item in Images)
            {
                AdvertImage advertImage = new AdvertImage();

                advertImage.ImagePath = await FileHelper.FileLoaderAsync(item, filePath: "/wwwroot/images/");

                advertImages.Add(advertImage);

            }

            _AdvertListingService.AddList(user, addListingView.Advert, advertImages, category);


            return RedirectToAction("Index", "Home");
        }

        public async Task<IActionResult> Detail(int? id)

		{
            //var advert = await _categoryAdvertService.                 _service.GetProductByCategoriesBrandsAsync(id);
            //await _advertService.ClickUpdating(id);
            if (id is not null)
            {
                var advert = await _advertService.FindAsync(id.Value);
                ViewData["userName"] = Request.Cookies["userName"];
                ViewData["userEmail"] = Request.Cookies["userEmail"];
                return View(advert);
            }
            else
            {
                return BadRequest();
            }
		}


        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<ActionResult> Create(string review, int id)
        {
            var advert = await _serviceAdvert.FindAsync(id);
            var user = await _UserService.FirstOrDefaultAsync(u => u.Email == Request.Cookies["userEmail"]);

            AdvertComment advertComment = new AdvertComment();
            advertComment.Advert = advert;
            advertComment.user = user;
            advertComment.Comment = review;
            _serviceComment.Add(advertComment);
            _serviceComment.SaveChanges();
            return RedirectToAction("Detail",new {id = advert.Id});

        }

        //[HttpPost]
        //[ValidateAntiForgeryToken]
        //public ActionResult Create(AdvertComment advertcommet)
        //{
        //    _serviceComment.Add(advertcommet);
        //    _serviceComment.SaveChanges();
        //    return RedirectToAction("Detail");

        //}


    }
}

aspnet-mvc-ads/Controllers/AuthController.cs
using App.Data.Entity;
using App.Service.Abstract;
using Microsoft.AspNetCore.Authentication;
using Microsoft.AspNetCore.Authentication.Cookies;
using Microsoft.AspNetCore.Mvc;
using System.Security.Claims;

namespace aspnet_mvc_ads.Controllers
{
    public class AuthController : Controller
    {
        private readonly IService<User> _userService;

        public AuthController(IService<User> userService)
        {
            _userService = userService;
        }

        public IActionResult Register()
        {
            return View();
        }

        [HttpPost]
        public IActionResult Register(User user)
        {
            if (ModelState.IsValid && user is not null)
            {
                _userService.Add(user);
                _userService.SaveChanges();
                return RedirectToAction(nameof(Login));
            }
            else
            {
                ModelState.AddModelError("", "Bilgilerinizi kontrol ediniz");
                return View(user);
            }

        }

        [Route("/Login")]
        public IActionResult Login()
        {
            return View();
        }

        [Route("/Login")]
        [HttpPost]
        public async Task<IActionResult> Login(string email, string password)
        {
            var user = _userService.Get(u => u.Email == email && u.Password == password);

            
            if (user is not null)
            {
                var userClaims = new List<Claim>()
                {
                    new Claim(ClaimTypes.Name, user.Name),
                    new Claim("Role", user.IsAdmin ? "Admin" : "User"),
                    new Claim("UserId", user.Id.ToString())
                };
                var guid  = Guid.NewGuid().ToString();
				Response.Cookies.Append("userguid", guid);
                Response.Cookies.Append("userName", user.Name);
                Response.Cookies.Append("userPhone", user.Phone);
                Response.Cookies.Append("userEmail", user.Email);
                Response.Cookies.Append("userAdress", user.Address);

                user.userGuid = guid;
                _userService.Update(user);
                _userService.SaveChanges();
				var userAuth = new ClaimsIdentity(userClaims, CookieAuthenticationDefaults.AuthenticationScheme);
                ClaimsPrincipal principal = new(userAuth);
                await HttpContext.SignInAsync(principal);


				return RedirectToAction("Index", "Home");
            }
            else
            {
                Response.Cookies.Append("userPhone", "");
                TempData["HataMesajı"] = "Bilgilerinizi kontrol edin!";
            }

            return View();
        }



        [Route("/Logout")]
        public async Task<IActionResult> Logout()
        {
            var user = _userService.Get(u => u.userGuid == Request.Cookies["userguid"]);
			user.userGuid = null;
			_userService.Update(user);
			_userService.SaveChanges();
			await HttpContext.SignOutAsync();
			Response.Cookies.Delete("userguid");
            Response.Cookies.Delete("userName");
            Response.Cookies.Delete("userPhone");
            Response.Cookies.Delete("userEmail");
            Response.Cookies.Delete("userAdress");
            

            return Redirect("/Login");
        }
    
       public async Task<IActionResult> ForgotPassword()
        {
            return View();
        }

        [HttpPost]
        public async Task<IActionResult> ForgotPassword(string email, string password)
        {
            var model = _userService.Get(u => u.Email == email);
            if (model == null)
            {
                return View(model);
            }
            model.Password = password;
            _userService.Update(model);
            _userService.SaveChanges();
            return RedirectToAction("Login");
        }

    }
}

aspnet-mvc-ads/Views/Shared/Components/NavBar/Default.cshtml
@model IEnumerable<Category>
@*
    For more information on enabling MVC for empty projects, visit https://go.microsoft.com/fwlink/?LinkID=397860
*@
@{
}
<section>
	<div class="container">
		<div class="row">
			<div class="col-md-12">
				<nav class="navbar navbar-expand-lg navbar-light navigation">
					<a class="navbar-brand" href="/">
						<img src="~/images/logo.png" alt="">
					</a>
					<button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarSupportedContent"
							aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
						<span class="navbar-toggler-icon"></span>
					</button>
					<div class="collapse navbar-collapse" id="navbarSupportedContent">
						<ul class="navbar-nav ml-auto main-nav ">
							<li class="nav-item active">
								<a class="nav-link" href="/">AnaSayfa</a>
							</li>
							<li class="nav-item dropdown dropdown-slide">
								<a class="nav-link dropdown-toggle" href="#" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
									Bağlantılar <span><i class="fa fa-angle-down"></i></span>
								</a>
								<!-- Dropdown list -->
								<div class="dropdown-menu">
									<a class="dropdown-item" asp-controller="Home" asp-action="AboutUs">Hakkımızda</a>
									<a class="dropdown-item" asp-controller="Home" asp-action="ContactUs">İletişim</a>
									<a class="dropdown-item" asp-controller="Home" asp-action="ErrorPage">404 Page</a>
									<a class="dropdown-item" asp-controller="Home" asp-action="Package">Package</a>
									<a class="dropdown-item" asp-controller="Advert" asp-action="Detail" asp-route-id="1">İlan Detay</a>
									<a class="dropdown-item" asp-controller="Home" asp-action="Store">Mağaza Detay</a>
									<a class="dropdown-item" asp-controller="Home" asp-action="Post">Ürün Detay</a>
									<a class="dropdown-item" asp-controller="Home" asp-action="Blog">Blog</a>

								</div>
							</li>
							<li class="nav-item dropdown dropdown-slide">
								<a class="nav-link dropdown-toggle" href="" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
									Kategoriler <span><i class="fa fa-angle-down"></i></span>
								</a>
								<!-- Dropdown list -->
								<div class="dropdown-menu">
									@foreach (var item in Model)
									{
										<a class="dropdown-item" asp-controller="Advert" asp-action="Search" asp-route-categoryID="@item.Id">@item.Name</a>


									}
								</div>
							</li>
						</ul>
						<ul class="navbar-nav ml-auto mt-10">
							@if (TempData["UserBilgisi"] is not null)
							{
								<li class="nav-item">
									<a class="nav-link login-button" asp-controller="Auth" asp-action="Logout">Çıkış Yap</a>
								</li>
								<li class="nav-item">
									<a class="nav-link text-white add-button" asp-controller="Advert" asp-action="AddListing"><i class="fa fa-plus-circle"></i> İlan Yayınla</a>
								</li>
							}
							else
							{
								<li class="nav-item">
									<a class="nav-link login-button" asp-controller="Auth" asp-action="Login">Giriş</a>
								</li>
							}
							
						</ul>
						@if (TempData["UserBilgisi"] is not null)
						{
							<ul class="navbar-nav mt-10">
								<li class="nav-item ml-3 pt-4">
									<a class="profile-icon" asp-controller="Home" asp-action="Profile"><i class="fa-solid fa-user fa-2xl"><h4 class="mt-2">@TempData["UserName"]</h4></i></a>
								</li>
							</ul>
						}
					</div>
				</nav>
			</div>
		</div>
	</div>
</section>